# Generated by Django 6.0.6 on 2026-07-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_book_delete_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued')], default='available', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='miniapp.book')),
            ],
            options={
                'ordering': ['book', 'copy_number'],
                'unique_together': {('book', 'copy_number')},
            },
        ),
    ]
