# Generated by Django 6.0.6 on 2026-07-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_book_category_book_shelf_location_issuerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='copy',
            field=models.ForeignKey(blank=True, help_text='Assigned once the librarian approves and hands over a specific copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_records', to='miniapp.bookcopy'),
        ),
    ]
