# Generated by Django 6.0.6 on 2026-07-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0007_alter_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
